
server:
  port: 8081

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Rabehi/store-ms.git
          searchPaths: config-data
          username: ${1}
          password: ${2}
  security:
    user:
      name: root
      password: s3cr3t